# https://github.com/marketplace/actions/automatic-releases
name: "Automated Forever v1 Release"
on:
  push:
    branches:
      - "main"
jobs:
  release:
    name: "Automatic Version Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Make Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # Git tag (for automatic releases)
          automatic_release_tag: "1.0.0"
          # Should this release be marked as a draft?
          draft: false
          # Should this release be marked as a pre-release?
          prerelease: false
          # Release title (for automatic releases)
          title: "Forever Version One - Automatic Latest Release"
          # Assets to upload to the release
          files: ""
